name: PrisonCore
version: '${project.version}'
main: me.thiboisweird.prisoncore.PrisonCore
api-version: 1.18
authors: [ ThiboIsEpic ]
description: ???
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - PlaceholderAPI
commands:
  vanish:
    usage: /vanish
    aliases: [ v ]
    description: Toggle your vanish state
  client:
    usage: /client
    aliases: [ c ]